site_name: Bonacchi Lab
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md
  - Team: team.md
  - News: news.md
  - Join Us: join.md
  - Contact: contact.md
  - For Lab Members:
    - Website Guide: website-guide.md
    - Lab Resources: resources.md
